# Generated by Django 5.1.15 on 2026-10-06 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0002_parkingslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(help_text='Calendar date of the reservation.', verbose_name='Reservation Date')),
                ('start_time', models.TimeField(help_text='Scheduled start time.', verbose_name='Start Time')),
                ('duration', models.PositiveIntegerField(default=1, help_text='Reservation duration in whole hours (1 to 24 hours).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Duration (Hours)')),
                ('end_time', models.TimeField(help_text='Scheduled end time calculated from start time + duration.', verbose_name='End Time')),
                ('start_datetime', models.DateTimeField(help_text='Timezone-aware start timestamp.', verbose_name='Start DateTime')),
                ('end_datetime', models.DateTimeField(help_text='Timezone-aware end timestamp.', verbose_name='End DateTime')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', help_text='Current lifecycle state of the reservation.', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parking_lot', models.ForeignKey(help_text='Facility where the slot is reserved.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.parkinglot', verbose_name='Parking Lot')),
                ('parking_slot', models.ForeignKey(help_text='Designated parking space allocated for this reservation.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.parkingslot', verbose_name='Parking Slot')),
                ('user', models.ForeignKey(help_text='User who booked this parking reservation.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['user', 'status'], name='res_user_status_idx'), models.Index(fields=['parking_lot', 'status'], name='res_lot_status_idx'), models.Index(fields=['parking_slot', 'status'], name='res_slot_status_idx'), models.Index(fields=['start_datetime', 'end_datetime'], name='res_time_range_idx'), models.Index(fields=['reservation_date', 'start_time'], name='res_date_time_idx'), models.Index(fields=['created_at'], name='res_created_idx')],
            },
        ),
    ]
