# Generated by Django 5.1.15 on 2026-10-02 15:16

import apps.parking.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Public display name of the parking facility.', max_length=200, verbose_name='Parking Name')),
                ('address', models.TextField(help_text='Full street address of the parking facility.', verbose_name='Address')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Geographic latitude (-90 to 90).', max_digits=10, validators=[apps.parking.models.validate_latitude], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Geographic longitude (-180 to 180).', max_digits=10, validators=[apps.parking.models.validate_longitude], verbose_name='Longitude')),
                ('total_slots', models.PositiveIntegerField(help_text='Total number of parking slots in this facility (must be > 0).', validators=[apps.parking.models.validate_positive], verbose_name='Total Slots')),
                ('available_slots', models.PositiveIntegerField(default=0, help_text='Current number of available slots. Day 03: stored value only. Real-time sync is Day 04+.', verbose_name='Available Slots')),
                ('price_per_hour', models.DecimalField(decimal_places=2, help_text='Hourly parking rate in Sri Lankan Rupees.', max_digits=8, validators=[apps.parking.models.validate_non_negative], verbose_name='Price per Hour (Rs.)')),
                ('opening_time', models.TimeField(help_text='Daily opening time of the parking facility.', verbose_name='Opening Time')),
                ('closing_time', models.TimeField(help_text='Daily closing time of the parking facility.', verbose_name='Closing Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(help_text='Parking Provider who manages this facility.', on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Parking Lot',
                'verbose_name_plural': 'Parking Lots',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner'], name='parking_owner_idx'), models.Index(fields=['latitude', 'longitude'], name='parking_geo_idx'), models.Index(fields=['price_per_hour'], name='parking_price_idx'), models.Index(fields=['available_slots'], name='parking_avail_idx'), models.Index(fields=['created_at'], name='parking_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_slots__gt', 0)), name='parking_total_slots_positive'), models.CheckConstraint(condition=models.Q(('available_slots__gte', 0)), name='parking_available_slots_non_negative'), models.CheckConstraint(condition=models.Q(('price_per_hour__gte', 0)), name='parking_price_non_negative')],
            },
        ),
    ]
