# Generated by Django 5.1.15 on 2026-10-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(help_text='Designation of the slot (e.g. A01, A02, B05).', max_length=20, verbose_name='Slot Number')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], default='AVAILABLE', help_text='Current occupancy state of the slot.', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parking_lot', models.ForeignKey(help_text='Facility this slot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkinglot', verbose_name='Parking Lot')),
            ],
            options={
                'verbose_name': 'Parking Slot',
                'verbose_name_plural': 'Parking Slots',
                'ordering': ['slot_number'],
                'indexes': [models.Index(fields=['parking_lot', 'status'], name='slot_lot_status_idx'), models.Index(fields=['parking_lot', 'slot_number'], name='slot_lot_num_idx'), models.Index(fields=['status'], name='slot_status_idx'), models.Index(fields=['created_at'], name='slot_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('parking_lot', 'slot_number'), name='unique_slot_per_lot')],
            },
        ),
    ]
